# Generated by Django 4.2rc1 on 2023-03-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Kурc USD')),
            ],
            options={
                'verbose_name': 'Kурc',
                'verbose_name_plural': 'Курсы',
                'db_table_comment': 'Таблица для обновления курса валют',
            },
        ),
    ]
